# Generated by Django 3.2.6 on 2021-12-28 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('college_description', models.TextField(null=True)),
                ('college_location', models.CharField(max_length=200, null=True)),
                ('college_fee', models.IntegerField()),
                ('college_image', models.FileField(null=True, upload_to='static/uploads')),
            ],
        ),
    ]
