# Generated by Django 3.2.6 on 2022-01-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20211228_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, null=True)),
                ('college_name', models.CharField(max_length=200, null=True)),
                ('stream', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
